version: '2.1'
services:
  mongo:
    image: mongo:3.5.11
    volumes:
      - mongo_data:/data/db
    restart: always
    healthcheck:
      test: "exit 0"
  redis:
    image: redis:3.2.10
    restart: always
    healthcheck:
      test: "exit 0"
  solr:
    image: openconceptlab/oclsolr:${ENVIRONMENT-production}
    volumes:
      - solr_data:/opt/solr/server/solr/collection1/data
    restart: always
    healthcheck:
      test: "exit 0"
  api:
    image: openconceptlab/oclapi:${ENVIRONMENT-production}
    depends_on:
      - mongo
      - solr
      - redis
    links:
      - "mongo:mongo.openconceptlab.org"
      - "redis:redis.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - WAIT_FOR="mongo.openconceptlab.org:27017 redis.openconceptlab.org:6379 solr.openconceptlab.org:8983"
      - ROOT_PASSWORD=Root123
      - OCL_API_TOKEN=891b4b17feab99f3ff7e5b5d04ccc5da7aa96da6
      - NEW_RELIC_API_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/authtoken/token/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
  celery:
    image: openconceptlab/oclapi:${ENVIRONMENT-production}
    command: bash run_celery.sh ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY} ${AWS_STORAGE_BUCKET_NAME}
    depends_on:
      - mongo
      - solr
      - redis
    links:
      - "mongo:mongo.openconceptlab.org"
      - "redis:redis.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
    environment:
      - C_FORCE_ROOT=1
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
    restart: always
    healthcheck:
      test: "exit 0"
  flower:
    image: openconceptlab/oclapi:${ENVIRONMENT-production}
    command: bash run_flower.sh
    depends_on:
      - redis
      - celery
    links:
      - "redis:redis.openconceptlab.org"
    environment:
      - C_FORCE_ROOT=1
    restart: always
    healthcheck:
      test: "exit 0"
volumes:
  mongo_data:
  solr_data: