version: '2.1'
services:
  mongo:
    image: mongo:3.2.11
    volumes:
      - mongo_data:/data/db
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  redis:
    image: redis:3.2.10
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  solr:
    image: openconceptlab/oclsolr:${ENVIRONMENT-production}
    volumes:
      - solr_data:/opt/solr/server/solr/collection1/data
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  api:
    image: openconceptlab/oclapi:${ENVIRONMENT-production}
    depends_on:
      - mongo
      - solr
      - redis
    links:
      - "mongo:mongo.openconceptlab.org"
      - "redis:redis.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
    ports:
      - "8000:8000"
    environment:
      - WAIT_FOR=mongo.openconceptlab.org:27017,redis.openconceptlab.org:6379,solr.openconceptlab.org:8983
      - ENVIRONMENT=${ENVIRONMENT-production}
      - ROOT_PASSWORD=${ROOT_PASSWORD-Root123}
      - OCL_API_TOKEN=${OCL_API_TOKEN-891b4b17feab99f3ff7e5b5d04ccc5da7aa96da6}
      - IMPORT_DEMO_DATA=${IMPORT_DEMO_DATA-false}
      - SECRET_KEY
      - SENTRY_DSN_KEY
      - EMAIL_HOST_PASSWORD
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
      - FLOWER_USER=${FLOWER_USER-floweruser}
      - FLOWER_PWD=${FLOWER_PWD-Flower123}
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/authtoken/token/"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  celery:
    image: openconceptlab/oclapi:${ENVIRONMENT-production}
    command: celery -A tasks worker -l INFO -Q default -n default --autoscale=15,3
    links:
      - "mongo:mongo.openconceptlab.org"
      - "redis:redis.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
      - "api:api.openconceptlab.org"
    environment:
      - C_FORCE_ROOT=1
      - SECRET_KEY
      - SENTRY_DSN_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  celery_bulk_import_0:
    image: openconceptlab/oclapi:${ENVIRONMENT-production}
    command: celery -A tasks worker -l INFO -Q bulk_import_0 -n bulk_import_0 -c 1
    links:
      - "mongo:mongo.openconceptlab.org"
      - "redis:redis.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
      - "api:api.openconceptlab.org"
    environment:
      - C_FORCE_ROOT=1
      - SECRET_KEY
      - SENTRY_DSN_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  celery_bulk_import_1:
    image: openconceptlab/oclapi:${ENVIRONMENT-production}
    command: celery -A tasks worker -l INFO -Q bulk_import_1 -n bulk_import_1 -c 1
    links:
      - "mongo:mongo.openconceptlab.org"
      - "redis:redis.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
      - "api:api.openconceptlab.org"
    environment:
      - C_FORCE_ROOT=1
      - SECRET_KEY
      - SENTRY_DSN_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  celery_bulk_import_2:
    image: openconceptlab/oclapi:${ENVIRONMENT-production}
    command: celery -A tasks worker -l INFO -Q bulk_import_2 -n bulk_import_2 -c 1
    links:
      - "mongo:mongo.openconceptlab.org"
      - "redis:redis.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
      - "api:api.openconceptlab.org"
    environment:
      - C_FORCE_ROOT=1
      - SECRET_KEY
      - SENTRY_DSN_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  celery_bulk_import_3:
    image: openconceptlab/oclapi:${ENVIRONMENT-production}
    command: celery -A tasks worker -l INFO -Q bulk_import_3 -n bulk_import_3 -c 1
    links:
      - "mongo:mongo.openconceptlab.org"
      - "redis:redis.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
      - "api:api.openconceptlab.org"
    environment:
      - C_FORCE_ROOT=1
      - SECRET_KEY
      - SENTRY_DSN_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  celery_bulk_import_4:
    image: openconceptlab/oclapi:${ENVIRONMENT-production}
    command: celery -A tasks worker -l INFO -Q bulk_import_4 -n bulk_import_4 -c 1
    links:
      - "mongo:mongo.openconceptlab.org"
      - "redis:redis.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
      - "api:api.openconceptlab.org"
    environment:
      - C_FORCE_ROOT=1
      - SECRET_KEY
      - SENTRY_DSN_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  celery_bulk_import_root:
    image: openconceptlab/oclapi:${ENVIRONMENT-production}
    command: celery -A tasks worker -l INFO -Q bulk_import_root -n bulk_import_root -c 1
    links:
      - "mongo:mongo.openconceptlab.org"
      - "redis:redis.openconceptlab.org"
      - "solr:solr.openconceptlab.org"
      - "api:api.openconceptlab.org"
    environment:
      - C_FORCE_ROOT=1
      - SECRET_KEY
      - SENTRY_DSN_KEY
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_STORAGE_BUCKET_NAME
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  flower:
    image: openconceptlab/oclapi:${ENVIRONMENT-production}
    command: celery -A tasks flower --basic_auth=${FLOWER_USER-floweruser}:${FLOWER_PWD-Flower123} --conf=flowerconfig.py
    ports:
      - "5555:5555"
    depends_on:
      - celery
    links:
      - "redis:redis.openconceptlab.org"
    environment:
      - C_FORCE_ROOT=1
      - SECRET_KEY
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
  backup:
    image: openmrs/cron-backup:1.0.0
    volumes:
      - mongo_data:/mongo_data
      - solr_data:/solr_data
      - ${BACKUP_DIR-./backups}:/backup
    environment:
      - DIRS=/mongo_data:mongo,/solr_data:solr
      - SCHEDULE=0 0 * * *
    restart: always
    healthcheck:
      test: "exit 0"
    logging:
      driver: "json-file"
      options:
        max-size: "10M"
        max-file: "10"
volumes:
  mongo_data:
  solr_data:
