version: '2.1'
services:
  mongo:
    ports:
      - "27017:27017"
    restart: "no"
  redis:
    ports:
      - "6379:6379"
    restart: "no"
  solr:
    build:
      context: ./solr
    ports:
      - "8983:8983"
    volumes:
      - ./solr/config:/opt/solr/server/solr/
    restart: "no"
  api:
    image: openconceptlab/oclapi:dev
    build:
      context: ./ocl
      dockerfile: Dockerfile-dev 
    ports:
      #ports for debugging
      - "8001:8001"
      - "2000:22"
    volumes:
      - ./ocl:/code
      - ./ocl/.pycharm_helpers:/root/.pycharm_helpers
    environment:
      - SSH=true
      - ENVIRONMENT=local
    restart: "no"
  celery:
    image: openconceptlab/oclapi:dev
    volumes:
      - ./ocl:/code
    restart: "no"
  flower:
    image: openconceptlab/oclapi:dev
    ports:
      - "5555:5555"
    volumes:
      - ./ocl:/code
    restart: "no"